sudo: false

language: go

go:
  - 1.8

services:
  - docker

env:
  global:
     - COMMIT=${TRAVIS_COMMIT::6}

before_install:
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
