sudo: false

language: go

go:
  - 1.8
  - 1.9

services:
  - docker

before_install:
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - go test -v ./...
