sudo: required

language: go

go:
  - 1.8
  - tip

services:
  - docker

env:
  global:
     - COMMIT=${TRAVIS_COMMIT::6}

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=coverage.out
$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build

after_success:
  - coveralls
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPO=mojlighetsministeriet/identity-provider
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo $REPO:$TAG:$COMMIT
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
