sudo: required

language: go

go:
  - 1.8

services:
  - docker

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - export REPO=mojlighetsministeriet/identity-provider
  - docker build -f Dockerfile -t $REPO .
  - docker tag $REPO:$COMMIT $REPO
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
