version: "3.3"

services:

  identity-provider:
    image: mojlighetsministeriet/identity-provider:master
    ports:
      - 80:1323
    networks:
      - frontend
      - backend
    depends_on:
      - database
    secrets:
      - private-key
      - smtp-password
      - database-connection
    environment:
      SMTP_HOST: smtp.glesys.se
      SMTP_PORT: 587
      SMTP_EMAIL: techsupport@mojlighetsministeriet.se
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  database:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: eUYP0mjoTt8YqCJBxa0bcrfN1miLzA
      MYSQL_DATABASE: identity-provider
      MYSQL_USER: identity-provider
      MYSQL_PASSWORD: eUYP0mjoTt8YqCJBxa0bcrfN1miLzA
    deploy:
      placement:
        constraints: [node.role == manager]

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8080:8080
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  backend:
    internal: true
  frontend:

volumes:
  database:

secrets:
  private-key:
    external:
      name: "private-key"
  smtp-password:
    external:
      name: "smtp-password"
  database-connection:
    external:
      name: "database-connection"
